"""
Based on supervised_trainer.py from the repo with Neil.
"""

import ast
import copy
import os
import torch
import gc
from contextlib import nullcontext
import vllm
from vllm import TokensPrompt
from dataclasses import dataclass
from torch.distributed.fsdp.fully_sharded_data_parallel import FullyShardedDataParallel as FSDP
from transformers import TrainerCallback, GenerationConfig
from accelerate.utils import gather_object
import jsonlines

from math_verify_compute_score import verl_math_verify_compute_score as compute_score
from check_parallel_format import check_parallel_worker_format

SPAWN_WORKERS = "<spawn_workers>"
UNSPAWN_WORKERS = "</spawn_workers>"
WORKER_STARTS = ["<worker_1>", "<worker_2>", "<worker_3>"]
WORKER_ENDS = ["</worker_1>", "</worker_2>", "</worker_3>"]

@dataclass
class ParallelGenArgs:
    max_parallel_rounds: int # max number of parallel rounds for each example
    max_tokens_in_parallel_round: int # upper bound on number of tokens generated by a worker during a parallel round

class ParallelGenerationEvalCallback(TrainerCallback):

    # Used to initialize VLLM Engine
    def get_engine_and_sampling_params(self, base_model_path):
        if torch.distributed.is_available() and torch.distributed.is_initialized():
            local_rank = torch.distributed.get_rank() % torch.cuda.device_count()
        else:
            local_rank = 0
        
        engine_args = vllm.EngineArgs(
            model=base_model_path,
            dtype=self.vllm_engine_args.dtype,
            enable_prefix_caching=False,
            block_size=self.vllm_engine_args.block_size,
            seed=self.vllm_engine_args.seed,
            gpu_memory_utilization=self.vllm_engine_args.gpu_memory_utilization,
            max_num_batched_tokens=self.vllm_engine_args.max_num_batched_tokens,
            max_num_seqs=self.vllm_engine_args.max_num_seqs,
            enforce_eager=self.vllm_engine_args.enforce_eager,
            max_model_len=self.vllm_engine_args.max_model_len,
            max_seq_len_to_capture=self.vllm_engine_args.max_seq_len_to_capture,
            device=f"cuda:{local_rank}",
            tensor_parallel_size=1,
            distributed_executor_backend="uni",
        )
        engine = vllm.LLMEngine.from_engine_args(engine_args)

        sampling_params = vllm.SamplingParams(
            n=1,
            temperature=self.generation_args.temperature,
            seed=self.vllm_engine_args.seed,
            max_tokens=self.generation_args.max_new_tokens,
            top_p=self.generation_args.top_p,
        )

        return engine, sampling_params
    
    def __init__(self, trainer, eval_dataset, tokenizer, generation_args, vllm_engine_args, eval_step_interval, eval_epoch_end, eval_best_attempts, eval_before_training, base_model_path, rollout_data_dir):
        """
        eval_dataset: A list of dicts, each with keys "prompt" and "ground_truth_answer"
        eval_step_interval: The number of steps between evaluations.
        eval_epoch_end: Whether to evaluate at the end of each epoch.
        vllm_engine_args:
            - dtype (bfloat16 preferred)
            - block_size (64 preferred)
            - seed
            - gpu_memory_utilization (0.95 preferred)
            - max_num_batched_tokens (30000 preferred)
            - max_num_seqs (2000 preferred)
            - enforce_eager (True preferred)
            - max_model_len (16384 preferred)
            - max_seq_len_to_capture (16384 preferred)
        generation_args:
            - temperature (set to 0 for greedy)
            - max_new_tokens
            - parallel_length_upper_bound
            - max_parallel_rounds

        We will always evaluate at the end of training.
        """
        self.trainer = trainer
        self.eval_dataset = eval_dataset
        self.tokenizer = tokenizer
        self.model = trainer.model
        self.generation_args = generation_args
        self.vllm_engine_args = vllm_engine_args
        self.eval_step_interval = eval_step_interval
        self.eval_epoch_end = eval_epoch_end
        self.eval_best_attempts = eval_best_attempts
        self.eval_before_training = eval_before_training
        self.base_model_path = base_model_path
        self.rollout_data_dir = rollout_data_dir
    
    def dump_rollouts(self, global_step, all_result_dict, scores, prompts):
        """
        all_result_dict has completions, parallel_response_lengths, total_response_tokens, satisfies_parallel_format
        scores is a list of 0/1 scores for each completion
        """
        os.makedirs(self.rollout_data_dir, exist_ok=True)
        filename = os.path.join(self.rollout_data_dir, f"{global_step}.jsonl")
        if os.path.exists(filename):
            import uuid
            filename = os.path.join(self.rollout_data_dir, f"{global_step}_{uuid.uuid4()}.jsonl")
        
        with jsonlines.open(filename, mode="w") as writer:
            n = len(scores)
            for i in range(n):
                current_entry = {}
                for k in all_result_dict.keys():
                    current_entry[k] = all_result_dict[k][i]
                current_entry["score"] = scores[i]
                current_entry["prompt"] = prompts[i]
                writer.write(current_entry)
        
        print(f"Dumped rollouts to {filename}")

    def obtain_parallel_completions(self, engine, prompts, seeds, sampling_params, parallel_gen_args):
        """
        - sampling_params is the base sampling params
        """

        """
        # First, add <think>\n to the prompts. This is supposed to be part
        of the response, so we are essentially just enforcing that the response
        starts with <think>\n.
        """
        PROMPT_SUFFIX = "<think>\n"
        prompts = [p + PROMPT_SUFFIX for p in prompts]

        max_parallel_rounds = parallel_gen_args.max_parallel_rounds
        rounds_left_per_prompt = [max_parallel_rounds] * len(prompts)
        tokens_left_per_prompt = [sampling_params.max_tokens] * len(prompts)
        completions = [""] * len(prompts)
        tokens_so_far = [[] for _ in range(len(prompts))]
        requests_per_prompt = [0] * len(prompts)
        parallel_length_per_prompt = [0] * len(prompts)
        response_length_per_prompt = [0] * len(prompts)

        for i, prompt in enumerate(prompts):
            current_sampling_params = copy.deepcopy(sampling_params)
            if current_sampling_params.temperature > 0:
                current_sampling_params.seed = seeds[i]
            current_sampling_params.stop = [SPAWN_WORKERS]
            current_sampling_params.include_stop_str_in_output = True
            current_sampling_params.skip_special_tokens = False
            request_id_dict = {
                "idx_in_batch": i,
                "round": 0,
                "single_thread": True,
            }
            requests_per_prompt[i] += 1

            tokenized_prompt = self.tokenizer.encode(prompt, add_special_tokens=False)
            tokens_so_far[i].extend(tokenized_prompt)
            engine.add_request(
                str(request_id_dict),
                TokensPrompt(prompt_token_ids=copy.deepcopy(tokens_so_far[i])),
                current_sampling_params
            )
        
        worker_outputs = []
        for _ in prompts:
            num_workers = len(WORKER_STARTS)
            worker_outputs.append([None] * num_workers)

        while engine.has_unfinished_requests():
            current_step_outputs = engine.step()

            for req_output in current_step_outputs:
                if req_output.finished:
                    request_id_dict = ast.literal_eval(req_output.request_id)
                    idx_in_batch = request_id_dict["idx_in_batch"]
                    output_str = req_output.outputs[0].text
                    generated_token_ids = req_output.outputs[0].token_ids
                    num_tokens_generated = len(generated_token_ids)

                    if request_id_dict["single_thread"]:
                        ####### Check if it is finished due to EOS or SPAWN_WORKERS
                        ####### IF SPAWN_WORKERS, CREATE NEW REQUESTS FOR EACH WORKER
                        completions[idx_in_batch] += output_str
                        tokens_so_far[idx_in_batch].extend(generated_token_ids)
                        tokens_left_per_prompt[idx_in_batch] -= num_tokens_generated
                        parallel_length_per_prompt[idx_in_batch] += num_tokens_generated
                        response_length_per_prompt[idx_in_batch] += num_tokens_generated
                        if tokens_left_per_prompt[idx_in_batch] > 0 and rounds_left_per_prompt[idx_in_batch] > 0 and req_output.outputs[0].stop_reason == SPAWN_WORKERS:
                            for i in range(len(WORKER_STARTS)):
                                worker_outputs[idx_in_batch][i] = None
                                request_id_dict = {
                                    "idx_in_batch": idx_in_batch,
                                    "round": requests_per_prompt[idx_in_batch],
                                    "single_thread": False,
                                    "worker_idx": i,
                                }
                                current_tokenized_prompt = copy.deepcopy(tokens_so_far[idx_in_batch])
                                current_tokenized_prompt.extend(self.tokenizer.encode(WORKER_STARTS[i], add_special_tokens=False))
                                worker_sampling_params = copy.deepcopy(sampling_params)
                                if worker_sampling_params.temperature > 0:
                                    worker_sampling_params.seed = seeds[idx_in_batch] + requests_per_prompt[idx_in_batch] + i
                                worker_sampling_params.max_tokens = min(
                                    tokens_left_per_prompt[idx_in_batch],
                                    parallel_gen_args.max_tokens_in_parallel_round
                                )
                                worker_sampling_params.stop = [WORKER_ENDS[i]]
                                worker_sampling_params.include_stop_str_in_output = True
                                worker_sampling_params.skip_special_tokens = False
                                engine.add_request(
                                    str(request_id_dict),
                                    TokensPrompt(prompt_token_ids=current_tokenized_prompt),
                                    worker_sampling_params
                                )
                            requests_per_prompt[idx_in_batch] += 1
                            rounds_left_per_prompt[idx_in_batch] -= 1
                    else:
                        ####### SAVE THE OUTPUT OF THIS WORKER
                        ####### IF ALL WORKERS ARE FINISHED, CREATE A NEW REQUEST FOR SINGLE THREAD
                        worker_idx = request_id_dict["worker_idx"]
                        worker_outputs[idx_in_batch][worker_idx] = req_output
                        tokens_left_per_prompt[idx_in_batch] -= num_tokens_generated
                        if all(worker_outputs[idx_in_batch]):
                            # Update parallel length
                            parallel_length_per_prompt[idx_in_batch] += max(
                                [
                                    len(worker_outputs[idx_in_batch][i].outputs[0].token_ids)
                                    for i in range(len(WORKER_STARTS))
                                ]
                            )
                            # Update response length
                            response_length_per_prompt[idx_in_batch] += sum(
                                [
                                    len(worker_outputs[idx_in_batch][i].outputs[0].token_ids)
                                    for i in range(len(WORKER_STARTS))
                                ]
                            )

                            ####### CREATE A NEW REQUEST FOR SINGLE THREAD
                            for i, w_start in enumerate(WORKER_STARTS):
                                completions[idx_in_batch] += w_start + worker_outputs[idx_in_batch][i].outputs[0].text
                                tokens_so_far[idx_in_batch].extend(self.tokenizer.encode(w_start, add_special_tokens=False))
                                tokens_so_far[idx_in_batch].extend(worker_outputs[idx_in_batch][i].outputs[0].token_ids)

                            completions[idx_in_batch] += UNSPAWN_WORKERS
                            tokens_so_far[idx_in_batch].extend(self.tokenizer.encode(UNSPAWN_WORKERS, add_special_tokens=False))
                            request_id_dict = {
                                "idx_in_batch": idx_in_batch,
                                "round": requests_per_prompt[idx_in_batch],
                                "single_thread": True,
                            }
                            requests_per_prompt[idx_in_batch] += 1

                            if tokens_left_per_prompt[idx_in_batch] > 0:
                                current_sampling_params = copy.deepcopy(sampling_params)
                                if current_sampling_params.temperature > 0:
                                    current_sampling_params.seed = seeds[idx_in_batch] + requests_per_prompt[idx_in_batch]
                                current_sampling_params.max_tokens = tokens_left_per_prompt[idx_in_batch]
                                current_sampling_params.stop = [SPAWN_WORKERS]
                                current_sampling_params.include_stop_str_in_output = True
                                current_sampling_params.skip_special_tokens = False
                                engine.add_request(
                                    str(request_id_dict),
                                    TokensPrompt(prompt_token_ids=copy.deepcopy(tokens_so_far[idx_in_batch])),
                                    current_sampling_params
                                )

        new_completions = []
        for completion in completions:
            skip_special_completions = self.tokenizer.encode(completion, add_special_tokens=False)
            skip_special_completions = self.tokenizer.decode(skip_special_completions, skip_special_tokens=True)
            new_completions.append(skip_special_completions)
        completions = new_completions

        """
        The completions do not contain <think>\n since it was included
        in the prompt, so we need to add it back.
        """
        completions = ["<think>\n" + c for c in completions]

        return {
            "completions": completions,
            "parallel_response_lengths": parallel_length_per_prompt,
            "total_response_tokens": response_length_per_prompt,
            "satisfies_parallel_format": [check_parallel_worker_format(completion) for completion in completions]
        }

    def on_epoch_end(self, args, state, control, **kwargs):
        if self.eval_epoch_end:
            return self.main_callback_method(args, state, control, **kwargs)
        else:
            return control

    def on_step_begin(self, args, state, control, **kwargs):
        if not self.eval_before_training:
            if state.global_step == 0:
                return control
        
        if state.global_step == 0 and self.eval_before_training:
            return self.main_callback_method(args, state, control, **kwargs)
        
        if self.eval_step_interval == -1:
            return control

        if state.global_step % self.eval_step_interval == 0:
            return self.main_callback_method(args, state, control, **kwargs)

    def on_train_end(self, args, state, control, **kwargs):
        return self.main_callback_method(args, state, control, **kwargs)
    
    def main_callback_method(self, args, state, control, **kwargs):
        prompts = [ex["prompt"] for ex in self.eval_dataset]
        ground_truth_answers = [ex["ground_truth_answer"] for ex in self.eval_dataset]
        metrics_dict = {}

        # Divide the work across batches/processes
        duplicated_prompts = []
        seeds = []
        duplicated_gts = []
        for idx in range(len(prompts)):
            current_prompt = prompts[idx]
            current_gt = ground_truth_answers[idx]
            duplicated_prompts.extend([current_prompt] * self.eval_best_attempts)
            duplicated_gts.extend([current_gt] * self.eval_best_attempts)
            seeds.extend([self.vllm_engine_args.seed + inc for inc in range(self.eval_best_attempts)])

        accelerator = self.trainer.accelerator
        all_result_dict = {
            "completions": [],
            "parallel_response_lengths": [],
            "total_response_tokens": [],
            "satisfies_parallel_format": []
        }

        print(f"Dividing duplicated prompts into {accelerator.num_processes} processes")
        num_prompts_before_padding = len(duplicated_prompts)
        if len(duplicated_prompts) % accelerator.num_processes != 0:
            extra_prompts = [duplicated_prompts[-1]] * (accelerator.num_processes - len(duplicated_prompts) % accelerator.num_processes)
            duplicated_prompts.extend(extra_prompts)
            extra_seeds = [seeds[-1]] * (accelerator.num_processes - len(seeds) % accelerator.num_processes)
            seeds.extend(extra_seeds)
        
        self.trainer.model_wrapped.eval()
        ctx = None
        if isinstance(self.trainer.model_wrapped, FSDP):
            ctx = FSDP.summon_full_params(self.trainer.model_wrapped, recurse=False)
        else:
            ctx = nullcontext()
        with ctx:
            engine, self.base_sampling_params = self.get_engine_and_sampling_params(self.base_model_path)
            model_wrapped = self.trainer.model_wrapped
            model_unwrapped = model_wrapped.module if hasattr(model_wrapped, "module") else model_wrapped
            vllm_model = engine.model_executor.driver_worker.model_runner.model
            # vllm_model.load_weights(model_unwrapped.named_parameters())
            def _clean_named_parameters(named_params):
                for name, param in named_params:
                    while "._fsdp_wrapped_module." in name:
                        name = name.replace("._fsdp_wrapped_module.", ".")
                    if name.endswith("._fsdp_wrapped_module"):
                        name = name.replace("._fsdp_wrapped_module", "")
                    yield name, param
            vllm_model.load_weights(_clean_named_parameters(model_unwrapped.named_parameters()))

            with accelerator.split_between_processes(list(zip(duplicated_prompts, seeds))) as per_process_prompts_and_seeds:
                per_process_prompts = [p[0] for p in per_process_prompts_and_seeds]
                per_process_seeds = [p[1] for p in per_process_prompts_and_seeds]
                parallel_gen_args = ParallelGenArgs(
                    max_parallel_rounds=self.generation_args.max_parallel_rounds,
                    max_tokens_in_parallel_round=self.generation_args.parallel_length_upper_bound
                )
                current_process_result_dict = self.obtain_parallel_completions(
                    engine=engine,
                    prompts=per_process_prompts,
                    seeds=per_process_seeds,
                    sampling_params=self.base_sampling_params,
                    parallel_gen_args=parallel_gen_args
                )
                for key in all_result_dict.keys():
                    all_result_dict[key] = gather_object(current_process_result_dict[key])
                    all_result_dict[key] = all_result_dict[key][:num_prompts_before_padding]
            
            del engine.model_executor
            del engine
            gc.collect()
            torch.cuda.empty_cache()
            torch.cuda.synchronize()
        
        # Compute metrics that are averaged
        avg_response_length = sum(all_result_dict["total_response_tokens"]) / len(all_result_dict["total_response_tokens"])
        metrics_dict["avg_response_length"] = avg_response_length
        avg_parallel_response_length = sum(all_result_dict["parallel_response_lengths"]) / len(all_result_dict["parallel_response_lengths"])
        metrics_dict["avg_parallel_response_length"] = avg_parallel_response_length
        avg_parallel_format_score = sum(all_result_dict["satisfies_parallel_format"]) / len(all_result_dict["satisfies_parallel_format"])
        metrics_dict["avg_parallel_format_score"] = avg_parallel_format_score

        degrees_of_parallelism = [total_length / parallel_length for total_length, parallel_length in zip(all_result_dict["total_response_tokens"], all_result_dict["parallel_response_lengths"])]
        metrics_dict["avg_degree_of_parallelism"] = sum(degrees_of_parallelism) / len(degrees_of_parallelism)

        # Compute pass rate and correct format rate based on # of attempts
        scores_by_prompt = []
        for j in range(len(prompts)):
            current_completions = all_result_dict["completions"][j * self.eval_best_attempts:(j + 1) * self.eval_best_attempts]
            gt_answer = ground_truth_answers[j]
            current_scores = [compute_score(completion, gt_answer) for completion in current_completions]
            scores_by_prompt.append(current_scores)
        for k in range(1, self.eval_best_attempts + 1):
            # current_pass_rate = sum(max(s[:k]) for s in scores_by_prompt) / len(scores_by_prompt)
            def pass_at_k_estimator(num_samples, num_correct, k):
                from scipy.special import comb
                numerator = comb(num_samples - num_correct, k)
                denominator = comb(num_samples, k)
                return 1 - numerator / denominator
            
            num_samples = self.eval_best_attempts
            correct_rates = [sum(s) for s in scores_by_prompt]
            pass_rates = [pass_at_k_estimator(num_samples, c, k) for c in correct_rates]
            metrics_dict[f"pass@{k}"] = sum(pass_rates) / len(pass_rates)
        format_scores_by_prompt = []
        # Compute pass rate and correct format rate
        for j in range(len(prompts)):
            format_list = all_result_dict["satisfies_parallel_format"][j * self.eval_best_attempts:(j + 1) * self.eval_best_attempts]
            format_list = [1 if f else 0 for f in format_list]
            format_scores_by_prompt.append(format_list)
        best_format_score = sum(max(s) for s in format_scores_by_prompt) / len(format_scores_by_prompt)
        metrics_dict[f"format_score_at_{self.eval_best_attempts}_attempts"] = best_format_score  

        if self.trainer.accelerator.is_main_process:
            # Save the rollouts for this step
            prompts_for_saving = []
            for p in prompts:
                prompts_for_saving.extend([p] * self.eval_best_attempts)
            scores_for_saving = []
            for s in scores_by_prompt:
                scores_for_saving.extend(s)
            self.dump_rollouts(
                global_step=state.global_step,
                all_result_dict=all_result_dict,
                scores=scores_for_saving,
                prompts=prompts_for_saving,
            )

            # Log degree of parallelism for correct responses
            sum_degree_of_parallelism = 0
            count_correct_responses = 0
            for degree_of_parallelism, score in zip(degrees_of_parallelism, scores_for_saving):
                if abs(score - 1.0) < 1e-4:
                    sum_degree_of_parallelism += degree_of_parallelism
                    count_correct_responses += 1
            
            if count_correct_responses > 0:
                avg_degree_parallel_correct = sum_degree_of_parallelism / count_correct_responses
                metrics_dict["avg_degree_parallel_correct"] = avg_degree_parallel_correct

        if self.trainer.accelerator.is_main_process:
            # Print a completion
            print(f"Completion: {all_result_dict['completions'][0]}")
            print(f"Completion: {all_result_dict['completions'][5]}")
            print(f"Completion: {all_result_dict['completions'][10]}")

        if self.trainer.accelerator.is_main_process:
            self.trainer.log(metrics_dict)   

        return control